import Head from "next/head";

import { v4 as uuid } from "uuid";

import { useEffect, useState } from "react";
import useSocket from "@/hooks/useSocket";
import useLocalStorage from "@/hooks/useLocalStorage";

import type { PanicInfo } from "@/types/interfaces";
import PanicItem from "@/components/PanicItem";

export default function Home() {
  const [panics, setPanics] = useState<PanicInfo[]>([
    { id: 1, nome: "Teste 1", unidade: "Avenida 1" },
    { id: 2, nome: "Teste 2", unidade: "Avenida 2" },
    { id: 3, nome: "Teste 3", unidade: "Avenida 3" },
  ]);

  const [seenPanics, setSeenPanics] = useLocalStorage<number[]>(
    "seen-panics",
    []
  );

  const socket = useSocket();
  useEffect(() => {
    if (socket) {
      socket.on("connect", () => {
        console.log("Connected");
      });

      socket.on("new-panic", (panic: PanicInfo) => {
        setPanics((st) => [panic, ...st]);
      });

      return () => {
        socket.off("connect");
        socket.off("new-panic");
      };
    }
  }, [socket]);

  const handleSee = (id: number) => {
    if (seenPanics && setSeenPanics instanceof Function) {
      setSeenPanics((st) => [...st!, id]);
    }
  };

  return (
    <>
      <Head>
        <title>Painel de Ocorrências</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-1 flex-wrap items-baseline justify-around gap-4 py-8">
        {seenPanics &&
          panics
            .filter((panic) => {
              console.log(seenPanics);
              if (seenPanics && typeof seenPanics === "object") {
                return !seenPanics.includes(panic.id);
              }
              return true;
            })
            .map((panic) => (
              <PanicItem key={uuid()} panic={panic} handleSee={handleSee} />
            ))}
      </div>
    </>
  );
}
